my_file=open("my_text.txt", "w")
my_file.write("Hi there, how are you?")
my_file.close()
my_file=open("my_text.txt", "r")
print(my_file.read())
my_file.close()
my_file=open("my_text.txt", "r")
print(my_file.readlines())
my_file.close()
