my_file=open("Names.txt", "w")
my_file.write('Bill\nBob\nJoe\nAndrew\nRicky\n')
my_file.close()
my_file=open('Names.txt', 'r')
print(my_file.read())
my_file.close()
my_file=open('Names.txt', 'a')
new_name=input('Enter a new name: ')
my_file.write(new_name)
my_file=open('Names.txt', 'r')
print(my_file.read())
my_file.close()
